# Below is the list of the component images with the digest. These need to be updated manually
# whenever a new bundle image is required (required also for releasing the index images).
# Make use of the `registry.stage.redhat.io` repository for using stage images and `registry.redhat.io` for prod images.
# This is currently sourced in `hack/bundle/render_templates.sh` to update the image references in the operator CSV.

# external-secrets operand image digest.
EXTERNAL_SECRETS_IMAGE=registry.redhat.io/external-secrets-operator/external-secrets-rhel9@sha256:9e07e95a6c0a7e8efabc6ed1692c0af5c0be11d92208b61836cef35af4300e35

# bitwarden-sdk-server operand image digest.
BITWARDEN_SDK_SERVER_IMAGE=registry.redhat.io/external-secrets-operator/bitwarden-sdk-server-rhel9@sha256:cef5721c26dc5370b3e8c4d7cd87825584d6c7c9af48324e476d0ce56a612442

# external-secrets-operator image digest.
EXTERNAL_SECRETS_OPERATOR_IMAGE=registry.redhat.io/external-secrets-operator/external-secrets-operator-rhel9@sha256:c7d54cdc1022a8d8123ee20a91247935a8bf845e597d9d12d6983c5d7e087e34
