# Below is the list of the component images with the digest. These need to be updated manually
# whenever a new bundle image is required (required also for releasing the index images).
# Make use of the `registry.stage.redhat.io` repository for using stage images and `registry.redhat.io` for prod images.
# This is currently sourced in `hack/bundle/render_templates.sh` to update the image references in the operator CSV.

# external-secrets operand image digest.
EXTERNAL_SECRETS_IMAGE=registry.redhat.io/external-secrets-operator/external-secrets-rhel9@sha256:a6e93b0490998452231aa558a0f664ec30ffedf161a477c5dfa3221a16ef56f1

# bitwarden-sdk-server operand image digest.
BITWARDEN_SDK_SERVER_IMAGE=registry.redhat.io/external-secrets-operator/bitwarden-sdk-server-rhel9@sha256:960fd17b5d871f6ef69469b4f78e2d72e8540c7dc84ed1540629d0620a0892af

# external-secrets-operator image digest.
EXTERNAL_SECRETS_OPERATOR_IMAGE=registry.redhat.io/external-secrets-operator/external-secrets-operator-rhel9@sha256:8e7a9b49e09b528d2c53d1aac86567375416a1efa38ae7e39fde5c22649015fc
