# Below is the list of the component images with the digest. These need to be updated manually
# whenever a new bundle image is required (required also for releasing the index images).
# Make use of the `registry.stage.redhat.io` repository for using stage images and `registry.redhat.io` for prod images.
# This is currently sourced in `hack/bundle/render_templates.sh` to update the image references in the operator CSV.

# external-secrets operand image digest.
EXTERNAL_SECRETS_IMAGE=registry.stage.redhat.io/external-secrets-operator/external-secrets-rhel9@sha256:5c9b694462ce93a61117311496834f88954ab01178ce24a04f003748694e15f5

# bitwarden-sdk-server operand image digest.
BITWARDEN_SDK_SERVER_IMAGE=registry.stage.redhat.io/external-secrets-operator/bitwarden-sdk-server-rhel9@sha256:8b5e72144defec569bcaba046ae2b5dc27bc8d9e2b2a91d3dc5a8c30e29f1075

# external-secrets-operator image digest.
EXTERNAL_SECRETS_OPERATOR_IMAGE=registry.stage.redhat.io/external-secrets-operator/external-secrets-operator-rhel9@sha256:fe6ad2eef8ed0ec4d49f0376204cda359e7f9b2862a78b9aa6602c90a68dab61
