apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/external-secrets-operator-release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/pull_request_number: "{{pull_request_number}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression:
      event == "pull_request" && target_branch
      == "main" && ( "catalogs/v4.22/***".pathChanged() || ".tekton/external-secrets-operator-index-4-22-pull-request.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: external-secrets-operator-index-4-22
    appstudio.openshift.io/component: external-secrets-operator-index-4-22
    pipelines.appstudio.openshift.io/type: build
  name: external-secrets-operator-index-4-22-on-pull-request
  namespace: external-secrets-oap-tenant
spec:
  params:
    - name: git-url
      value: "{{source_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/external-secrets-oap-tenant/external-secrets-operator-4-22/external-secrets-operator-index-4-22:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: dockerfile
      value: Containerfile
    - name: path-context
      value: catalogs/v4.22
    - name: build-args
      value: []
  pipelineRef:
    name: fbc-build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-external-secrets-operator-index-4-22
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
